version: "3.6"

networks:
  cr-net: # shared container network     

volumes:
  shared-data: # shared voume between the two containers
 
services:
  REST-API:
    build: 
      context: ./rest_api # Docker image is rebuild from directory which contains Dockerfile
    depends_on: 
      - cron-job # cron job container should start first
    container_name: rest-api
    image: openaq_api
    networks:
      - cr-net
    volumes:
      - shared-data:/src/shared-data
    ports:
      - "3838:3838"
    restart: always

  cron-job:
    build: 
      context: ./cron # Docker image is rebuild from directory which contains Dockerfile
    container_name: cron-job
    image: openaq_extraction
    networks:
      - cr-net 
    volumes:
      - shared-data:/src/shared-data
    restart: always

 
 
